In [1]:
import numpy as np

import sys
import time
import matplotlib.pyplot as plt
%matplotlib inline

## introduction numpy

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
print(a[0])
print(a[1])

1
2


In [4]:
l = range(100)
print(sys.getsizeof(5)*len(l))

2800


In [5]:
array = np.arange(100)
print(array.size*array.itemsize)

800


In [6]:
SIZE = 10000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

# py list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ", (time.time()-start)*100)

# np list
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*100)

python list took:  0.11599063873291016
numpy took:  0.03161430358886719


In [7]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [8]:
a1+a2

array([5, 7, 9])

In [9]:
a1-a2

array([-3, -3, -3])

In [10]:
a1*a2

array([ 4, 10, 18])

In [11]:
a1/a2

array([0.25, 0.4 , 0.5 ])

## basic array operations

In [12]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
a.ndim

[[1 2]
 [3 4]
 [5 6]]


2

In [13]:
x = np.array([1, 2, 3])
x.ndim

1

In [14]:
y = np.zeros((2, 3, 4))
print(y)
y.ndim

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


3

In [15]:
a.itemsize

8

In [16]:
a.dtype

dtype('int64')

In [17]:
a = np.array([[1,2], [3,4], [5,6]], dtype=np.float64)
print(a)
print(a.dtype)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
float64


In [18]:
a.shape

(3, 2)

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
l = range(5)
print(l[0])
print(l[1])

0
1


In [22]:
np.arange(1,5)

array([1, 2, 3, 4])

In [23]:
np.arange(1,5,3)

array([1, 4])

In [24]:
s = np.linspace(1,5,10)
s

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [25]:
s = np.linspace(1,5,5)
s

array([1., 2., 3., 4., 5.])

In [26]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [27]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
a.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [29]:
a.ravel()

array([1., 2., 3., 4., 5., 6.])

In [30]:
print(a.min())
print(a.max())
print(a.mean())
print(a.sum())

1.0
6.0
3.5
21.0


In [31]:
print(a.sum(axis=0))
print(a.sum(axis=1))

[ 9. 12.]
[ 3.  7. 11.]


In [32]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [33]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [34]:
np.sqrt(3)

1.7320508075688772

In [35]:
np.std(a)

1.707825127659933

In [36]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

In [37]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [39]:
a+b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [40]:
a*b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [41]:
a/b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [42]:
b = b.reshape(3,2)
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [43]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

## slicing/stacking arrays, indexing with boolean arrays

In [44]:
n = [6,7,8]
n

[6, 7, 8]

In [45]:
print(n[0:2])
print(n[-1])

[6, 7]
8


In [46]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
x[1,2]

6

In [48]:
x[0:2,2]

array([3, 6])

In [49]:
x[-1,:]

array([7, 8, 9])

In [50]:
x[:,-1]

array([3, 6, 9])

In [51]:
for row in x:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [52]:
for flat in x.flat:
    print(flat, end=' ')

1 2 3 4 5 6 7 8 9 

In [53]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [54]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [55]:
b = np.arange(6, 12).reshape(3,2)
a = np.arange(6).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [56]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [57]:
np.hstack((a, b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [58]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [59]:
result = np.hsplit(a,3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [60]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [61]:
result_t = np.vsplit(a,2)
result_t

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [62]:
n = np.arange(12).reshape(3,4)
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
bb = n > 4
bb

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
n[bb]

array([ 5,  6,  7,  8,  9, 10, 11])

In [65]:
n[bb]=-1
n

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

## iterate numpy array using nditer

In [66]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
for row in a:
    for cell in row:
        print(cell, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [72]:
for row in a.flatten():
    print(row, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [74]:
for x in np.nditer(a, order="C"):
    print(x, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [75]:
for x in np.nditer(a, order="F"):
    print(x, end=' ')

0 4 8 1 5 9 2 6 10 3 7 11 

In [76]:
for x in np.nditer(a, order="F", flags=['external_loop']):
    print(x, end=' ')

[0 4 8] [1 5 9] [ 2  6 10] [ 3  7 11] 

In [80]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=x*x

In [81]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [83]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [89]:
for x, y in np.nditer([a,b]):
    print(x, y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
