## Спектральное разложение

Спектральное разложение матрици $-$ это такое представление **квадратной** матрици $A$ в виде произведения трех матриц, $A=V\Lambda V^{-1}$, где:
  - $V$ $-$ матрица, столбци которой являются ортонормированными собственными векторами матрици $A$
  - $\Lambda$ $-$ диагональная матрица с соответствеющими собственными значениями на главной диагонали
  - $V^{-1}$ $-$ матрица, обратная матрице $V$


Дальнейшее обозначение: $X = S^T \cdot D \cdot S$

In [30]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

A = np.array([[1.0,2,-1],
              [2,2,5],
              [-1,5,-3]])

A

array([[ 1.,  2., -1.],
       [ 2.,  2.,  5.],
       [-1.,  5., -3.]])

In [0]:
v, w = np.linalg.eigh(A)

In [32]:
print(v, "\n") #собственные значения
print(w) #собственные вектора

[-6.58  1.15  5.43] 

[[-0.25  0.93 -0.27]
 [ 0.53 -0.11 -0.84]
 [-0.81 -0.35 -0.47]]


In [33]:
D = np.diag(v)
D

array([[-6.58,  0.  ,  0.  ],
       [ 0.  ,  1.15,  0.  ],
       [ 0.  ,  0.  ,  5.43]])

In [34]:
S = w.T
S

array([[-0.25,  0.53, -0.81],
       [ 0.93, -0.11, -0.35],
       [-0.27, -0.84, -0.47]])

In [35]:
S.T

array([[-0.25,  0.93, -0.27],
       [ 0.53, -0.11, -0.84],
       [-0.81, -0.35, -0.47]])

In [36]:
# S и S.T - ортоганальные
np.dot(S.T, S)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# S.T, D, S - действительно образуют спектральное разложение
print(A, "\n") # изначальная матрица
print(np.dot(np.dot(S.T, D), S))

[[ 1.  2. -1.]
 [ 2.  2.  5.]
 [-1.  5. -3.]] 

[[ 1.  2. -1.]
 [ 2.  2.  5.]
 [-1.  5. -3.]]


## Сингулярное разложение
Сингулярное разложение матрици $M$ порядка $m\ x\  n$ является разложение матрици $M=U \Sigma V^*$ где
  - $\Sigma$ - матрица $m\ x\  n$ с неотрицательными элементами, у которой элементы, лежащие на главной диагонали - это сингулярные числа (а все элементы, не лежащие на главной диагонали, являются нулевыми)
  - а матрица $U$ (порядка $m$) и матрица $V$ (порядка $n$) $-$ это две унитарные матрици, состоящие из левых и правых сингулярных векторов соответственно (а $V^*$ $-$ это сопряженно-транспонированныя матрица к $V$) 


Далее обозначение вида: $X = U \cdot D \cdot V$

In [40]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

X = np.array([[1,2,0],
              [0,0,5],
              [3,-4,2],
              [1,6,5],
              [0,1,0]])

X

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [0]:
U, s, W = np.linalg.svd(X)

In [42]:
U

array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
       [ 0.39, -0.53,  0.61, -0.43,  0.03],
       [-0.14, -0.82, -0.52,  0.14,  0.07],
       [ 0.89,  0.06, -0.25,  0.38, -0.06],
       [ 0.08,  0.11, -0.08, -0.11,  0.98]])

In [43]:
V = W.T
V

array([[ 0.07, -0.37, -0.93],
       [ 0.72,  0.67, -0.21],
       [ 0.69, -0.65,  0.31]])

In [44]:
print(s, "\n")

D = np.zeros_like(X, dtype=float)
print(D, "\n")

D[np.diag_indices(min(X.shape))] = s
print(D, "\n")

[8.82 6.14 2.53] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]] 



In [45]:
np.dot(U.T, U) #скалярное произведение

array([[ 1.,  0., -0.,  0., -0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [-0.,  0.,  1., -0., -0.],
       [ 0.,  0., -0.,  1., -0.],
       [-0.,  0., -0., -0.,  1.]])

In [46]:
np.dot(V.T, V)

array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [-0., -0.,  1.]])

In [47]:
print(X, "\n","-"*50 ,"\n")
print(U, "\n")
print(D, "\n")
print(V, "\n")

[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]] 
 -------------------------------------------------- 

[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]] 

[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]] 

[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]] 



In [48]:
# U, D, V.T - действительно спектрально разложены
print(X, "\n")
print(np.dot(np.dot(U,D), V.T))

[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]] 

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


In [0]:
pass